### ISSUE TITLE
Build failure on case-sensitive file systems

### ISSUE THREAD

**Issue by matt1432** [thlucas1/SpotifyWebApiPython#1]
When trying to build this module, I get this error:

```console
 getting list of files in path "docspdoc/build/" ...
 getting list of files in path "docspdoc/build/spotifywebapiPython/" ...
 Traceback (most recent call last):
   File "/build/source/nix_run_setup", line 8, in <module>
     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
   File "setup.py", line 52, in <module>
     ('../../spotifywebapiPython/docs/spotifywebapiPython', getDirFilesList('docspdoc/build/spotifywebapiPython/')),
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "setup.py", line 26, in getDirFilesList
     dir_list = os.listdir(pathName)
                ^^^^^^^^^^^^^^^^^^^^
 FileNotFoundError: [Errno 2] No such file or directory: 'docspdoc/build/spotifywebapiPython/'
```

I fixed it on my end by replacing `docspdoc/build/spotifywebapiPython/` with `docspdoc/build/spotifywebapipython/`

**Comment by matt1432** [comment]
Also, not directly related to this issue, but why `note that urllib3 version must be less than 2!`?

I've been using this with the `urllib3` from `nixpkgs`, which is `2.2.2` and it's been working

**Comment by thlucas1** [comment]
I'm a Windows guy, so forgot that case matters on some file systems.  In hindsight, I should have named the library `spotifywebapipython` as well (instead of `spotifywebapiPython`.  

I'll get the `/docs/spotifywebapiPython` reference changed in the next release.

As for the `urllib3` ... here is what I have in my developer notes about why I use that specific version:
```
URLLIB3 issues with kwargs in Home Assistant
urllib3 version must be less than 2.0 in order to be used with Home Assistant!
otherwise, you get weird **kwargs errors in HA, especially the media_player.play_media calls!!!
```

**Comment by matt1432** [comment]
Thanks!

Huh alright, guess I'll have to switch to an older version too

**Comment by thlucas1** [comment]
Are you working on some sort of Spotify UI with this API?  Just curious how you are using it.

I have a SpotifyPlus Card in the works, and am almost ready to release it.

**Comment by matt1432** [comment]
I'm working on an AI voice assistant with https://github.com/TheNimaj/extended_ollama_conversation and working on playing music with it rn.

That's cool! Would definitely like to have that

**Comment by thlucas1** [comment]
The AI voice stuff sounds really cool as well; I just have not had enough time to look into using it.

Keep an eye on the HA community forum - I'll be sending out a notice within the next couple of weeks about the new SpotifyPlus Card.  I'm pretty excited about it, and hope I do it justice. lol

**Comment by thlucas1** [comment]
@matt1432 
Forgot to mention - most of the services provided by the `spotifywebapiPython` package are available via the SpotifyPlus integration.  Check out the [Services Provided](https://github.com/thlucas1/homeassistantcomponent_spotifyplus/wiki/Services-Provided) wiki docs for details.

Just thought I would mention it, in case you are doing anything in your AI component that needs to call a service via a script.

**Comment by thlucas1** [comment]
@matt1432 
I put together a [SpotifyPlus Card UI Beta Test](https://github.com/thlucas1/spotifyplus_card/discussions/8) announcement, if you're still interested in beta testing the new SpotifyPlus user-interface for Home Assistant?  Just reply to the discussion link if you are, and feel free to download the card and give it a whirl.

Thanks - Todd
